version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1 
jobs:
  build:
    docker:
      - image: "cmig/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install 
          command: | 
             npm run frontend:install
      - run:
          name: Back-End Install 
          command: | 
             npm run backend:install
      - run:
          name: Front-End Build 
          command: | 
             npm run frontend:build
      - run:
          name: Front-End Build 
          command: | 
             npm run frontend:build
      - run:
          name: Front-End Deploy 
          command: | 
             npm run frontend:deploy
      - run:
          name: Front-End Deploy 
          command: | 
             npm run frontend:deploy
